<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="54" failed="0" total="72" passed="18">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="4736" started-at="2015-09-28T15:48:36Z" finished-at="2015-09-28T15:48:41Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="4736" started-at="2015-09-28T15:48:36Z" finished-at="2015-09-28T15:48:41Z">
      <class name="discuss.repositories.SuperCrudTest">
        <test-method status="SKIP" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.repositories.SuperCrudTest@1442d7b5]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="SKIP" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.repositories.SuperCrudTest@1442d7b5]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.SuperCrudTest@1442d7b5]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.repositories.SuperCrudTest@1442d7b5]" name="create" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.repositories.SuperCrudTest@1442d7b5]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.SuperCrudTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SuperCrudTest.read()[pri:0, instance:discuss.repositories.SuperCrudTest@1442d7b5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SuperCrudTest.read()[pri:0, instance:discuss.repositories.SuperCrudTest@1442d7b5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="SKIP" signature="update()[pri:0, instance:discuss.repositories.SuperCrudTest@1442d7b5]" name="update" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.SuperCrudTest.read" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SuperCrudTest.update()[pri:0, instance:discuss.repositories.SuperCrudTest@1442d7b5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SuperCrudTest.update()[pri:0, instance:discuss.repositories.SuperCrudTest@1442d7b5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- update -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.SuperCrudTest@1442d7b5]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.repositories.SuperCrudTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.repositories.SuperCrudTest@1442d7b5]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
        <test-method status="SKIP" signature="delete()[pri:0, instance:discuss.repositories.SuperCrudTest@1442d7b5]" name="delete" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.SuperCrudTest.update" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SuperCrudTest.delete()[pri:0, instance:discuss.repositories.SuperCrudTest@1442d7b5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SuperCrudTest.delete()[pri:0, instance:discuss.repositories.SuperCrudTest@1442d7b5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
      </class> <!-- discuss.repositories.SuperCrudTest -->
      <class name="discuss.repositories.HarvestCrudTest">
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.HarvestCrudTest@69a10787]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.repositories.HarvestCrudTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.HarvestCrudTest@69a10787]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="SKIP" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.repositories.HarvestCrudTest@69a10787]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="SKIP" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.repositories.HarvestCrudTest@69a10787]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.repositories.HarvestCrudTest@69a10787]" name="create" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.repositories.HarvestCrudTest@69a10787]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.repositories.HarvestCrudTest@69a10787]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.HarvestCrudTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HarvestCrudTest.read()[pri:0, instance:discuss.repositories.HarvestCrudTest@69a10787] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HarvestCrudTest.read()[pri:0, instance:discuss.repositories.HarvestCrudTest@69a10787] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="SKIP" signature="delete()[pri:0, instance:discuss.repositories.HarvestCrudTest@69a10787]" name="delete" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.HarvestCrudTest.update" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HarvestCrudTest.delete()[pri:0, instance:discuss.repositories.HarvestCrudTest@69a10787] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HarvestCrudTest.delete()[pri:0, instance:discuss.repositories.HarvestCrudTest@69a10787] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method status="SKIP" signature="update()[pri:0, instance:discuss.repositories.HarvestCrudTest@69a10787]" name="update" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.HarvestCrudTest.read" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HarvestCrudTest.update()[pri:0, instance:discuss.repositories.HarvestCrudTest@69a10787] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HarvestCrudTest.update()[pri:0, instance:discuss.repositories.HarvestCrudTest@69a10787] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- update -->
      </class> <!-- discuss.repositories.HarvestCrudTest -->
      <class name="discuss.services.SuperServiceTest">
        <test-method status="SKIP" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.services.SuperServiceTest@7181ae3f]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.services.SuperServiceTest@7181ae3f]" name="create" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.SuperServiceTest@7181ae3f]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="1" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.services.SuperServiceTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.SuperServiceTest@7181ae3f]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="SKIP" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.services.SuperServiceTest@7181ae3f]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.services.SuperServiceTest@7181ae3f]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.services.SuperServiceTest@7181ae3f]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.services.SuperServiceTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SuperServiceTest.read()[pri:0, instance:discuss.services.SuperServiceTest@7181ae3f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SuperServiceTest.read()[pri:0, instance:discuss.services.SuperServiceTest@7181ae3f] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
      </class> <!-- discuss.services.SuperServiceTest -->
      <class name="discuss.repositories.SalesCrudTest">
        <test-method status="SKIP" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.repositories.SalesCrudTest@679b62af]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="SKIP" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.repositories.SalesCrudTest@679b62af]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.SalesCrudTest@679b62af]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.repositories.SalesCrudTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.repositories.SalesCrudTest@679b62af]" name="create" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.repositories.SalesCrudTest@679b62af]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.SalesCrudTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SalesCrudTest.read()[pri:0, instance:discuss.repositories.SalesCrudTest@679b62af] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SalesCrudTest.read()[pri:0, instance:discuss.repositories.SalesCrudTest@679b62af] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.SalesCrudTest@679b62af]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.repositories.SalesCrudTest@679b62af]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
        <test-method status="SKIP" signature="delete()[pri:0, instance:discuss.repositories.SalesCrudTest@679b62af]" name="delete" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.SalesCrudTest.update" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SalesCrudTest.delete()[pri:0, instance:discuss.repositories.SalesCrudTest@679b62af] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SalesCrudTest.delete()[pri:0, instance:discuss.repositories.SalesCrudTest@679b62af] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method status="SKIP" signature="update()[pri:0, instance:discuss.repositories.SalesCrudTest@679b62af]" name="update" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.SalesCrudTest.read" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SalesCrudTest.update()[pri:0, instance:discuss.repositories.SalesCrudTest@679b62af] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SalesCrudTest.update()[pri:0, instance:discuss.repositories.SalesCrudTest@679b62af] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- update -->
      </class> <!-- discuss.repositories.SalesCrudTest -->
      <class name="discuss.factories.HiveFactoryTest">
        <test-method status="PASS" signature="testCreate()[pri:0, instance:discuss.factories.HiveFactoryTest@1188e820]" name="testCreate" duration-ms="3" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate -->
        <test-method status="PASS" signature="testUpdate()[pri:0, instance:discuss.factories.HiveFactoryTest@1188e820]" name="testUpdate" duration-ms="0" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdate -->
      </class> <!-- discuss.factories.HiveFactoryTest -->
      <class name="discuss.services.SaleServiceTest">
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.SaleServiceTest@166fa74d]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="SKIP" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.services.SaleServiceTest@166fa74d]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.SaleServiceTest@166fa74d]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.services.SaleServiceTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.services.SaleServiceTest@166fa74d]" name="create" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="SKIP" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.services.SaleServiceTest@166fa74d]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.services.SaleServiceTest@166fa74d]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.services.SaleServiceTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SaleServiceTest.read()[pri:0, instance:discuss.services.SaleServiceTest@166fa74d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SaleServiceTest.read()[pri:0, instance:discuss.services.SaleServiceTest@166fa74d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.services.SaleServiceTest@166fa74d]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
      </class> <!-- discuss.services.SaleServiceTest -->
      <class name="discuss.repositories.BeekeeperCrudTest">
        <test-method status="PASS" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.repositories.BeekeeperCrudTest@6cc7b4de]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="1" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="FAIL" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.repositories.BeekeeperCrudTest@6cc7b4de]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:36Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:36Z">
          <exception class="java.lang.IllegalStateException">
            <message>
              <![CDATA[Failed to load ApplicationContext]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:94)
	at org.springframework.test.context.DefaultTestContext.getApplicationContext(DefaultTestContext.java:72)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:170)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:110)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:212)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:552)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'harvestServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: discuss.respository.HarvestRepository discuss.Services.Impl.HarvestServiceImpl.repository; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [discuss.respository.HarvestRepository] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1210)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:687)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
	at org.springframework.boot.test.SpringApplicationContextLoader.loadContext(SpringApplicationContextLoader.java:104)
	at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:68)
	at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:86)
	... 33 more
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: discuss.respository.HarvestRepository discuss.Services.Impl.HarvestServiceImpl.repository; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [discuss.respository.HarvestRepository] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 48 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [discuss.respository.HarvestRepository] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1301)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1047)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
	... 50 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalStateException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.BeekeeperCrudTest@6cc7b4de]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.repositories.BeekeeperCrudTest@6cc7b4de]" name="create" duration-ms="1" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.BeekeeperCrudTest@6cc7b4de]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="1" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.repositories.BeekeeperCrudTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="SKIP" signature="delete()[pri:0, instance:discuss.repositories.BeekeeperCrudTest@6cc7b4de]" name="delete" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.BeekeeperCrudTest.update" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BeekeeperCrudTest.delete()[pri:0, instance:discuss.repositories.BeekeeperCrudTest@6cc7b4de] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BeekeeperCrudTest.delete()[pri:0, instance:discuss.repositories.BeekeeperCrudTest@6cc7b4de] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method status="SKIP" signature="update()[pri:0, instance:discuss.repositories.BeekeeperCrudTest@6cc7b4de]" name="update" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.BeekeeperCrudTest.read" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BeekeeperCrudTest.update()[pri:0, instance:discuss.repositories.BeekeeperCrudTest@6cc7b4de] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BeekeeperCrudTest.update()[pri:0, instance:discuss.repositories.BeekeeperCrudTest@6cc7b4de] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- update -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.repositories.BeekeeperCrudTest@6cc7b4de]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.BeekeeperCrudTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BeekeeperCrudTest.read()[pri:0, instance:discuss.repositories.BeekeeperCrudTest@6cc7b4de] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BeekeeperCrudTest.read()[pri:0, instance:discuss.repositories.BeekeeperCrudTest@6cc7b4de] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.repositories.BeekeeperCrudTest@6cc7b4de]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
      </class> <!-- discuss.repositories.BeekeeperCrudTest -->
      <class name="discuss.factories.LocationFactoryTest">
        <test-method status="PASS" signature="testCreate()[pri:0, instance:discuss.factories.LocationFactoryTest@290dbf45]" name="testCreate" duration-ms="1" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate -->
        <test-method status="PASS" signature="testUpdate()[pri:0, instance:discuss.factories.LocationFactoryTest@290dbf45]" name="testUpdate" duration-ms="0" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdate -->
      </class> <!-- discuss.factories.LocationFactoryTest -->
      <class name="discuss.factories.SalesFactoryTest">
        <test-method status="PASS" signature="testCreate()[pri:0, instance:discuss.factories.SalesFactoryTest@17776a8]" name="testCreate" duration-ms="2" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate -->
        <test-method status="PASS" signature="testUpdate()[pri:0, instance:discuss.factories.SalesFactoryTest@17776a8]" name="testUpdate" duration-ms="0" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdate -->
      </class> <!-- discuss.factories.SalesFactoryTest -->
      <class name="discuss.services.BucketServiceTest">
        <test-method status="SKIP" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.services.BucketServiceTest@d6da883]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.BucketServiceTest@d6da883]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="SKIP" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.services.BucketServiceTest@d6da883]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.services.BucketServiceTest@d6da883]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.services.BucketServiceTest@d6da883]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.services.BucketServiceTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BucketServiceTest.read()[pri:0, instance:discuss.services.BucketServiceTest@d6da883] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BucketServiceTest.read()[pri:0, instance:discuss.services.BucketServiceTest@d6da883] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.services.BucketServiceTest@d6da883]" name="create" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.BucketServiceTest@d6da883]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.services.BucketServiceTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
      </class> <!-- discuss.services.BucketServiceTest -->
      <class name="discuss.repositories.LocationCrudTest">
        <test-method status="SKIP" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.repositories.LocationCrudTest@2f490758]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="SKIP" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.repositories.LocationCrudTest@2f490758]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.LocationCrudTest@2f490758]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.repositories.LocationCrudTest@2f490758]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.LocationCrudTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LocationCrudTest.read()[pri:0, instance:discuss.repositories.LocationCrudTest@2f490758] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LocationCrudTest.read()[pri:0, instance:discuss.repositories.LocationCrudTest@2f490758] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.LocationCrudTest@2f490758]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.repositories.LocationCrudTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.repositories.LocationCrudTest@2f490758]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
        <test-method status="SKIP" signature="delete()[pri:0, instance:discuss.repositories.LocationCrudTest@2f490758]" name="delete" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.LocationCrudTest.update" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LocationCrudTest.delete()[pri:0, instance:discuss.repositories.LocationCrudTest@2f490758] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LocationCrudTest.delete()[pri:0, instance:discuss.repositories.LocationCrudTest@2f490758] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method status="SKIP" signature="update()[pri:0, instance:discuss.repositories.LocationCrudTest@2f490758]" name="update" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.LocationCrudTest.read" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LocationCrudTest.update()[pri:0, instance:discuss.repositories.LocationCrudTest@2f490758] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LocationCrudTest.update()[pri:0, instance:discuss.repositories.LocationCrudTest@2f490758] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- update -->
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.repositories.LocationCrudTest@2f490758]" name="create" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
      </class> <!-- discuss.repositories.LocationCrudTest -->
      <class name="discuss.services.CustomerServiceTest">
        <test-method status="SKIP" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.services.CustomerServiceTest@799d4f69]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="SKIP" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.services.CustomerServiceTest@799d4f69]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.services.CustomerServiceTest@799d4f69]" name="create" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.CustomerServiceTest@799d4f69]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.services.CustomerServiceTest@799d4f69]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.services.CustomerServiceTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CustomerServiceTest.read()[pri:0, instance:discuss.services.CustomerServiceTest@799d4f69] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CustomerServiceTest.read()[pri:0, instance:discuss.services.CustomerServiceTest@799d4f69] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.CustomerServiceTest@799d4f69]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.services.CustomerServiceTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.services.CustomerServiceTest@799d4f69]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
      </class> <!-- discuss.services.CustomerServiceTest -->
      <class name="discuss.repositories.CustomerCrudTest">
        <test-method status="SKIP" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.repositories.CustomerCrudTest@32a068d1]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="SKIP" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.repositories.CustomerCrudTest@32a068d1]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.repositories.CustomerCrudTest@32a068d1]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.CustomerCrudTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CustomerCrudTest.read()[pri:0, instance:discuss.repositories.CustomerCrudTest@32a068d1] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CustomerCrudTest.read()[pri:0, instance:discuss.repositories.CustomerCrudTest@32a068d1] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="SKIP" signature="delete()[pri:0, instance:discuss.repositories.CustomerCrudTest@32a068d1]" name="delete" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.CustomerCrudTest.update" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CustomerCrudTest.delete()[pri:0, instance:discuss.repositories.CustomerCrudTest@32a068d1] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CustomerCrudTest.delete()[pri:0, instance:discuss.repositories.CustomerCrudTest@32a068d1] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method status="SKIP" signature="update()[pri:0, instance:discuss.repositories.CustomerCrudTest@32a068d1]" name="update" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.CustomerCrudTest.read" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CustomerCrudTest.update()[pri:0, instance:discuss.repositories.CustomerCrudTest@32a068d1] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CustomerCrudTest.update()[pri:0, instance:discuss.repositories.CustomerCrudTest@32a068d1] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- update -->
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.CustomerCrudTest@32a068d1]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.repositories.CustomerCrudTest@32a068d1]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.repositories.CustomerCrudTest@32a068d1]" name="create" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.CustomerCrudTest@32a068d1]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.repositories.CustomerCrudTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
      </class> <!-- discuss.repositories.CustomerCrudTest -->
      <class name="discuss.services.HiveServiceTest">
        <test-method status="SKIP" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.services.HiveServiceTest@365c30cc]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="SKIP" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.services.HiveServiceTest@365c30cc]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.services.HiveServiceTest@365c30cc]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.services.HiveServiceTest@365c30cc]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.services.HiveServiceTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HiveServiceTest.read()[pri:0, instance:discuss.services.HiveServiceTest@365c30cc] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HiveServiceTest.read()[pri:0, instance:discuss.services.HiveServiceTest@365c30cc] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.services.HiveServiceTest@365c30cc]" name="create" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.HiveServiceTest@365c30cc]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.services.HiveServiceTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.HiveServiceTest@365c30cc]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
      </class> <!-- discuss.services.HiveServiceTest -->
      <class name="discuss.repositories.SubLocationCrudTest">
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.repositories.SubLocationCrudTest@6e2c9341]" name="create" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="SKIP" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.repositories.SubLocationCrudTest@6e2c9341]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.SubLocationCrudTest@6e2c9341]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="SKIP" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.repositories.SubLocationCrudTest@6e2c9341]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.SubLocationCrudTest@6e2c9341]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.repositories.SubLocationCrudTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.repositories.SubLocationCrudTest@6e2c9341]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
        <test-method status="SKIP" signature="delete()[pri:0, instance:discuss.repositories.SubLocationCrudTest@6e2c9341]" name="delete" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.SubLocationCrudTest.update" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SubLocationCrudTest.delete()[pri:0, instance:discuss.repositories.SubLocationCrudTest@6e2c9341] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SubLocationCrudTest.delete()[pri:0, instance:discuss.repositories.SubLocationCrudTest@6e2c9341] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.repositories.SubLocationCrudTest@6e2c9341]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.SubLocationCrudTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SubLocationCrudTest.read()[pri:0, instance:discuss.repositories.SubLocationCrudTest@6e2c9341] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SubLocationCrudTest.read()[pri:0, instance:discuss.repositories.SubLocationCrudTest@6e2c9341] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="SKIP" signature="update()[pri:0, instance:discuss.repositories.SubLocationCrudTest@6e2c9341]" name="update" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.SubLocationCrudTest.read" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SubLocationCrudTest.update()[pri:0, instance:discuss.repositories.SubLocationCrudTest@6e2c9341] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SubLocationCrudTest.update()[pri:0, instance:discuss.repositories.SubLocationCrudTest@6e2c9341] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- update -->
      </class> <!-- discuss.repositories.SubLocationCrudTest -->
      <class name="discuss.repositories.BucketCrudTest">
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.repositories.BucketCrudTest@2bbaf4f0]" name="create" duration-ms="1" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.BucketCrudTest@2bbaf4f0]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="SKIP" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.repositories.BucketCrudTest@2bbaf4f0]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="SKIP" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.repositories.BucketCrudTest@2bbaf4f0]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.repositories.BucketCrudTest@2bbaf4f0]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.BucketCrudTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BucketCrudTest.read()[pri:0, instance:discuss.repositories.BucketCrudTest@2bbaf4f0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BucketCrudTest.read()[pri:0, instance:discuss.repositories.BucketCrudTest@2bbaf4f0] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.BucketCrudTest@2bbaf4f0]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.repositories.BucketCrudTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="SKIP" signature="update()[pri:0, instance:discuss.repositories.BucketCrudTest@2bbaf4f0]" name="update" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.BucketCrudTest.read" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BucketCrudTest.update()[pri:0, instance:discuss.repositories.BucketCrudTest@2bbaf4f0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BucketCrudTest.update()[pri:0, instance:discuss.repositories.BucketCrudTest@2bbaf4f0] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- update -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.repositories.BucketCrudTest@2bbaf4f0]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
        <test-method status="SKIP" signature="delete()[pri:0, instance:discuss.repositories.BucketCrudTest@2bbaf4f0]" name="delete" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.BucketCrudTest.update" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BucketCrudTest.delete()[pri:0, instance:discuss.repositories.BucketCrudTest@2bbaf4f0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BucketCrudTest.delete()[pri:0, instance:discuss.repositories.BucketCrudTest@2bbaf4f0] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
      </class> <!-- discuss.repositories.BucketCrudTest -->
      <class name="discuss.repositories.HiveCrudTest">
        <test-method status="SKIP" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.repositories.HiveCrudTest@530612ba]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.HiveCrudTest@530612ba]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.repositories.HiveCrudTest@530612ba]" name="create" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="SKIP" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.repositories.HiveCrudTest@530612ba]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.repositories.HiveCrudTest@530612ba]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.repositories.HiveCrudTest@530612ba]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.repositories.HiveCrudTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.repositories.HiveCrudTest@530612ba]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.HiveCrudTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HiveCrudTest.read()[pri:0, instance:discuss.repositories.HiveCrudTest@530612ba] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HiveCrudTest.read()[pri:0, instance:discuss.repositories.HiveCrudTest@530612ba] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="SKIP" signature="delete()[pri:0, instance:discuss.repositories.HiveCrudTest@530612ba]" name="delete" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.HiveCrudTest.update" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HiveCrudTest.delete()[pri:0, instance:discuss.repositories.HiveCrudTest@530612ba] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HiveCrudTest.delete()[pri:0, instance:discuss.repositories.HiveCrudTest@530612ba] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method status="SKIP" signature="update()[pri:0, instance:discuss.repositories.HiveCrudTest@530612ba]" name="update" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.repositories.HiveCrudTest.read" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HiveCrudTest.update()[pri:0, instance:discuss.repositories.HiveCrudTest@530612ba] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HiveCrudTest.update()[pri:0, instance:discuss.repositories.HiveCrudTest@530612ba] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- update -->
      </class> <!-- discuss.repositories.HiveCrudTest -->
      <class name="discuss.services.SubLocationServiceTest">
        <test-method status="SKIP" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.services.SubLocationServiceTest@76a4d6c]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="SKIP" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.services.SubLocationServiceTest@76a4d6c]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.SubLocationServiceTest@76a4d6c]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.SubLocationServiceTest@76a4d6c]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.services.SubLocationServiceTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.services.SubLocationServiceTest@76a4d6c]" name="create" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.services.SubLocationServiceTest@76a4d6c]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.services.SubLocationServiceTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SubLocationServiceTest.read()[pri:0, instance:discuss.services.SubLocationServiceTest@76a4d6c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SubLocationServiceTest.read()[pri:0, instance:discuss.services.SubLocationServiceTest@76a4d6c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.services.SubLocationServiceTest@76a4d6c]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
      </class> <!-- discuss.services.SubLocationServiceTest -->
      <class name="discuss.factories.BucketFactoryTest">
        <test-method status="PASS" signature="testCreate()[pri:0, instance:discuss.factories.BucketFactoryTest@70beb599]" name="testCreate" duration-ms="5" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate -->
        <test-method status="PASS" signature="testUpdate()[pri:0, instance:discuss.factories.BucketFactoryTest@70beb599]" name="testUpdate" duration-ms="0" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdate -->
      </class> <!-- discuss.factories.BucketFactoryTest -->
      <class name="discuss.factories.HarvestFactoryTest">
        <test-method status="PASS" signature="testCreate()[pri:0, instance:discuss.factories.HarvestFactoryTest@4e41089d]" name="testCreate" duration-ms="0" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate -->
        <test-method status="PASS" signature="testUpdate()[pri:0, instance:discuss.factories.HarvestFactoryTest@4e41089d]" name="testUpdate" duration-ms="0" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdate -->
      </class> <!-- discuss.factories.HarvestFactoryTest -->
      <class name="discuss.services.BeekeeperServiceTest">
        <test-method status="SKIP" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.services.BeekeeperServiceTest@70a9f84e]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="SKIP" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.services.BeekeeperServiceTest@70a9f84e]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.BeekeeperServiceTest@70a9f84e]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.BeekeeperServiceTest@70a9f84e]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.services.BeekeeperServiceTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.services.BeekeeperServiceTest@70a9f84e]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.services.BeekeeperServiceTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BeekeeperServiceTest.read()[pri:0, instance:discuss.services.BeekeeperServiceTest@70a9f84e] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BeekeeperServiceTest.read()[pri:0, instance:discuss.services.BeekeeperServiceTest@70a9f84e] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.services.BeekeeperServiceTest@70a9f84e]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.services.BeekeeperServiceTest@70a9f84e]" name="create" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
      </class> <!-- discuss.services.BeekeeperServiceTest -->
      <class name="discuss.factories.SuperFactoryTest">
        <test-method status="PASS" signature="testCreate()[pri:0, instance:discuss.factories.SuperFactoryTest@1ee807c6]" name="testCreate" duration-ms="2" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate -->
        <test-method status="PASS" signature="testUpdate()[pri:0, instance:discuss.factories.SuperFactoryTest@1ee807c6]" name="testUpdate" duration-ms="0" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdate -->
      </class> <!-- discuss.factories.SuperFactoryTest -->
      <class name="discuss.factories.CustomerFactoryTest">
        <test-method status="PASS" signature="testCreate()[pri:0, instance:discuss.factories.CustomerFactoryTest@12028586]" name="testCreate" duration-ms="1" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate -->
        <test-method status="PASS" signature="testUpdate()[pri:0, instance:discuss.factories.CustomerFactoryTest@12028586]" name="testUpdate" duration-ms="0" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdate -->
      </class> <!-- discuss.factories.CustomerFactoryTest -->
      <class name="discuss.services.HarvestServiceTest">
        <test-method status="SKIP" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.services.HarvestServiceTest@276438c9]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="SKIP" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.services.HarvestServiceTest@276438c9]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.services.HarvestServiceTest@276438c9]" name="create" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.HarvestServiceTest@276438c9]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.HarvestServiceTest@276438c9]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.services.HarvestServiceTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.services.HarvestServiceTest@276438c9]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.services.HarvestServiceTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HarvestServiceTest.read()[pri:0, instance:discuss.services.HarvestServiceTest@276438c9] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HarvestServiceTest.read()[pri:0, instance:discuss.services.HarvestServiceTest@276438c9] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.services.HarvestServiceTest@276438c9]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
      </class> <!-- discuss.services.HarvestServiceTest -->
      <class name="discuss.factories.SubLocationFactoryTest">
        <test-method status="PASS" signature="testCreate()[pri:0, instance:discuss.factories.SubLocationFactoryTest@1e4a7dd4]" name="testCreate" duration-ms="1" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate -->
        <test-method status="PASS" signature="testUpdate()[pri:0, instance:discuss.factories.SubLocationFactoryTest@1e4a7dd4]" name="testUpdate" duration-ms="0" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdate -->
      </class> <!-- discuss.factories.SubLocationFactoryTest -->
      <class name="discuss.factories.BeekeeperFactoryTest">
        <test-method status="PASS" signature="testCreate()[pri:0, instance:discuss.factories.BeekeeperFactoryTest@4e4aea35]" name="testCreate" duration-ms="10" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate -->
        <test-method status="PASS" signature="testUpdate()[pri:0, instance:discuss.factories.BeekeeperFactoryTest@4e4aea35]" name="testUpdate" duration-ms="0" started-at="2015-09-28T17:48:36Z" finished-at="2015-09-28T17:48:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdate -->
      </class> <!-- discuss.factories.BeekeeperFactoryTest -->
      <class name="discuss.services.LocationServiceTest">
        <test-method status="SKIP" signature="springTestContextPrepareTestInstance()[pri:0, instance:discuss.services.LocationServiceTest@33b37288]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="SKIP" signature="springTestContextBeforeTestClass()[pri:0, instance:discuss.services.LocationServiceTest@33b37288]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="SKIP" signature="create()[pri:0, instance:discuss.services.LocationServiceTest@33b37288]" name="create" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="SKIP" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.LocationServiceTest@33b37288]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="SKIP" signature="read()[pri:0, instance:discuss.services.LocationServiceTest@33b37288]" name="read" duration-ms="0" started-at="2015-09-28T17:48:41Z" depends-on-methods="discuss.services.LocationServiceTest.create" finished-at="2015-09-28T17:48:41Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LocationServiceTest.read()[pri:0, instance:discuss.services.LocationServiceTest@33b37288] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LocationServiceTest.read()[pri:0, instance:discuss.services.LocationServiceTest@33b37288] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1099)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:discuss.services.LocationServiceTest@33b37288]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void discuss.services.LocationServiceTest.create() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:discuss.services.LocationServiceTest@33b37288]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2015-09-28T17:48:41Z" finished-at="2015-09-28T17:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
      </class> <!-- discuss.services.LocationServiceTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
